name: Check For New Release

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: bash .github/checkForNewRelease.sh