name: Build Docker Image

on:
  workflow_run:
    workflows: ["Check For New Release"]
    types: [completed]
  workflow_dispatch:
    inputs:
      forceBuild:
        description: 'Force build manually'
        required: true
        default: 'yes'

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.inputs.forceBuild == 'yes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: automad/automad:latest