name: Build Docker Image

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:
    inputs:
      forceBuild:
        description: 'Force build manually'
        required: true
        default: 'yes'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      days: ${{ steps.getDays.outputs.days }}
    steps:
      - name: Get number of days since latest release
        id: getDays
        run: |
          days=$(curl -s https://api.github.com/repos/marcantondahmen/automad/releases/latest | jq -r "((now - (.published_at | fromdateiso8601)) / (60 * 60 * 24) | trunc)")
          echo "$days since the latest release was published"
          echo "::set-output name=days::$days"
  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.days == '0' || github.event.inputs.forceBuild == 'yes' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: automad/automad:latest